#!/usr/bin/env ruby

require 'ec2tools'
require 'optparse'

ec2 = EC2.new
options = {}
@private = false
@deploy_conf_mode = false
opt = OptionParser.new do |opt|
  opt.on('-k KEY') { |v| options[:key] = v }
  opt.on('-s VAL') { |v| options[:num] = (v.to_i - 1) }
  opt.on('-p')     { |v| @mode = :private }
  opt.on('-i')     { |v| @mode = :instance }
  opt.on('-c')     { |v| @deploy_conf_mode = true }
  opt.parse!(ARGV)
end

key = case @mode
      when :private
        'privateDnsName'
      when :instance
        'instanceId'
      else
        'dnsName'
      end

hostnames = ec2.servers(options).map do |instance|
  instance[key]
end

if @deploy_conf_mode
  puts '"' + hostnames.join("\"\n") + '"'
else
  hostnames.each do |hostname|
    puts hostname
  end
end
